### ISSUE TITLE
$WINDOWID could be incorrect

### ISSUE THREAD

**Issue by haolian9** [Kody-Quintana/x11-border-color.nvim#1]
hi wow! that's an interesting idea and useful customization.

i just skimmed its implementation, and noticed that the use of `$WINDOWID` env could be wrong in the following cases:
* nvim is running in a tmux session, and user may attach to the same session through many clients
* nvim is running as a remote client by `nvim --remote-ui --server path`

i tried to figure out a fix for them, failed eventually.

**Comment by Kody-Quintana** [comment]
hey thanks for checking this out. for these situations i think the best bet is to just disable the plugin. I've expanded some configuration [here](https://github.com/kody-quintana/x11-border-color.nvim/compare/main...set_default_disable_behavior) to disable the functionality if:
  * `TMUX` env var is set to any value
  * `--remote-ui` is in any of the args

i'll wrap this up later this week when i get some time

**Comment by haolian9** [comment]
glad to get your reply! adding these limits to the plugin is a good take IMHO.

yet the logic in the set_default_disable_behavior branch could be simplified IMO: if the `config.disable_*` is really necessary (to me, it's fine to be hardcoded), how about making it callable? something in my mind like this and user can re-configure it:
```
config.disable = function()
  if os.getenv("TMUX") ~= nil then return true end

  for _, arg in ipairs(vim.v.argv) do
    if arg == "--remote-ui" then return true end
  end

  return false
end
```

**Comment by Kody-Quintana** [comment]
I think you may be right, and I am already hardcoding several other things that disable the plugin anyway so I will probably simplify this more.

But, now that I think about it, shouldn't this plugin also be disabled when `--listen` is one of the args? I do not use this functionality of nvim so I am not sure of the workflows people may have with these options

**Comment by haolian9** [comment]
speaking of `--listen/--remote-ui/--server`, i just discovered that feature while watching the neovimconf 2023, i have no much experience on it so far.

but yes, now i believe `--remote-ui` should never occur in `vim.v.argv`, since the lua code will always run on the server side which is started by `nvim --listen path [--headless]`.

**Comment by Kody-Quintana** [comment]
Ok I'm going to keep this simple and just do:
```lua
if os.getenv('TMUX') ~= nil then
  return nil
end

for _, arg in ipairs(vim.v.argv) do
  for _, disabling_arg in ipairs({
    '--remote-ui',
    '--listen',
  }) do
    if arg == disabling_arg then
      return nil
    end
  end
end
```

Thanks for bringing this to my attention. If there are other args or env vars that need to be checked I'll add them in the future
